[package]
name = "wod"
version = "0.1.1"
edition = "2021"
description = "A simple library to write on diff."
license = "MIT"

[dev-dependencies]
tempfile = "3.3.0"
rustc-hash = "1.1.0"

[dependencies]
